#!/bin/sh

# Usage:
# cc -o prog $CFLAGS `libdevmem-config --cflags` prog.c `libdevmem-config --libs`

### FIXME fix when installed in a different dir!
mydir=$(readlink -e $(dirname $0))

while [ -n "$1" ]
do
	case "$1" in
      --cflags)
          #  - Env vars used to detect physical base address of CL2400
          echo -n '-DENV_MBASE=\"CL2400_PCI_BASE_ADDR\" -DENV_MEM_END=\"CL2400_PCI_LAST_ADDR\"'
          #  - Include path for libdevmem.h
          echo -n " -I $mydir"
      ;;
      --libs)
          # No lib, compile the .c file:
          echo -n " $mydir/libdevmem.c"
      ;;
      *)
         echo >&2 "Invalid option. Use --libs or --cflags"
         exit 1
      ;;
      esac
      shift
done

